version: "3.8"

services:
  pdtm-server:
    build: .
    container_name: pdtm-server
    restart: always
    ports:
      - "4497:4497"
    env_file:
      - .env
    volumes:
      - /pdt/Pdtm-server/log:/app/log
      - /pdt/Pdtm-server/apk:/app/apk